# Test of features for ex 16


In [1]:
import os
import numpy as np
import tensorflow as tf

In [2]:
os.getcwd()

'd:\\Utilisateurs\\Damien\\Drive\\drive_damien\\Projet_dvlpt\\Cours_dvlpt\\MOOC_Luc_Jaulin\\RobMOOC\\robmoocpy'

In [7]:

def make_phi_hat():
    model_path = 'phi_hat_model.keras'
    data_path = 'deepboatdata.txt'

    if os.path.exists(model_path):
        return tf.keras.models.load_model(model_path)
    
    else:
        if os.path.exists(data_path):
            print("Training new model...")
            
            phi_hat_model = tf.keras.Sequential([
                tf.keras.layers.Input(shape=(5,)),
                tf.keras.layers.Dense(16, activation='relu'),
                tf.keras.layers.Dense(16, activation='relu'),
                tf.keras.layers.Dense(3)
            ])

            phi_hat_model.compile(optimizer='adam', loss='mse')
            exp_data = np.loadtxt('deepboatdata.txt')
            X_train = exp_data[:, :5]
            y_train = exp_data[:, 5:]
            phi_hat_model.fit(X_train, y_train, epochs=5, batch_size=32)

            # we should save the generated model to use it later
            phi_hat_model.save(model_path)
            return phi_hat_model
    
        elif not os.path.exists('deepboatdata.txt'):
            print("Error: deepboatdata.txt not found.")
            return None

In [12]:
phi_hat_model = make_phi_hat()

In [13]:
phi_hat_model_2 = make_phi_hat()
phi_hat_model_2

<Sequential name=sequential, built=True>

In [14]:

def phi_hat(vx,vy,w,u1,u2, phi_hat_model):
    input_data = np.array([[vx, vy, w, u1, u2]])
    dvx, dvy, dw = phi_hat_model.predict(input_data)[0]
    # sortie = tolist(phi_hat_model.predict(input_data).flatten())
    return dvx, dvy, dw

In [15]:
phi_hat(0.5, 0.2, 0.1, 1.0, 0.5, phi_hat_model)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step


(np.float32(1.1856234), np.float32(-0.17536072), np.float32(0.28576022))

## ex 35

In [3]:
from roblib import *  # available at https://www.ensta-bretagne.fr/jaulin/roblib.py

m=20
p=10*rand(2,m)
p

array([[0.43644322, 6.5252834 , 5.4527335 , 4.81425622, 9.75093905,
        5.11071519, 3.64955193, 5.6507575 , 8.43618749, 9.88093394,
        1.07839883, 1.88817947, 9.18366821, 2.60483903, 0.31379976,
        4.809886  , 7.20593883, 1.20541649, 2.28606707, 0.58316033],
       [4.52881633, 0.16494574, 7.93892316, 5.19947311, 3.33105591,
        2.58628623, 2.21968162, 0.5314026 , 1.50048765, 2.45484092,
        8.8883055 , 1.80713466, 3.15867222, 2.76548664, 2.96975904,
        9.3576734 , 9.61148364, 5.24540914, 1.82937614, 7.83365248]])

In [ ]:
2*p.T

array([[0.43644322, 4.52881633],
       [6.5252834 , 0.16494574],
       [5.4527335 , 7.93892316],
       [4.81425622, 5.19947311],
       [9.75093905, 3.33105591],
       [5.11071519, 2.58628623],
       [3.64955193, 2.21968162],
       [5.6507575 , 0.5314026 ],
       [8.43618749, 1.50048765],
       [9.88093394, 2.45484092],
       [1.07839883, 8.8883055 ],
       [1.88817947, 1.80713466],
       [9.18366821, 3.15867222],
       [2.60483903, 2.76548664],
       [0.31379976, 2.96975904],
       [4.809886  , 9.3576734 ],
       [7.20593883, 9.61148364],
       [1.20541649, 5.24540914],
       [2.28606707, 1.82937614],
       [0.58316033, 7.83365248]])

Use a horizontal concatenation (axis=1). For example, if `p` is `2×m` so that `p.T` is `m×2`, and you have another matrix `Q` of shape `m×k` you want on the right:

```python
C = np.concatenate((p.T, Q), axis=1)
# or equivalently
C = np.hstack((p.T, Q))
```

If you want to add a single column vector `v` (length `m`) on the right of `p.T`:

```python
v = np.arange(m)          # shape (m,)
C = np.hstack((p.T, v[:, None]))  # v[:, None] -> shape (m,1)
```

In [9]:
ones(m)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [13]:
A = np.hstack((p.T, ones(m).T[:,None]))
A

array([[0.43644322, 4.52881633, 1.        ],
       [6.5252834 , 0.16494574, 1.        ],
       [5.4527335 , 7.93892316, 1.        ],
       [4.81425622, 5.19947311, 1.        ],
       [9.75093905, 3.33105591, 1.        ],
       [5.11071519, 2.58628623, 1.        ],
       [3.64955193, 2.21968162, 1.        ],
       [5.6507575 , 0.5314026 , 1.        ],
       [8.43618749, 1.50048765, 1.        ],
       [9.88093394, 2.45484092, 1.        ],
       [1.07839883, 8.8883055 , 1.        ],
       [1.88817947, 1.80713466, 1.        ],
       [9.18366821, 3.15867222, 1.        ],
       [2.60483903, 2.76548664, 1.        ],
       [0.31379976, 2.96975904, 1.        ],
       [4.809886  , 9.3576734 , 1.        ],
       [7.20593883, 9.61148364, 1.        ],
       [1.20541649, 5.24540914, 1.        ],
       [2.28606707, 1.82937614, 1.        ],
       [0.58316033, 7.83365248, 1.        ]])

In [17]:
n = 3  # number of columns
ones_matrix = np.ones((m, n))
ones_matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
n = m-len(p.T[1])
n

18

In [21]:
ones_matrix = np.ones((m, n))
len(ones_matrix)

20

In [22]:
ones_matrix.shape

(20, 18)

In [31]:
A = np.hstack((2*p.T, ones_matrix))
A.shape

(20, 20)

In [34]:
A = np.hstack((p.T, ones((m, 1)), np.zeros((m, n-1))))


In [35]:
A

array([[0.43644322, 4.52881633, 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [6.5252834 , 0.16494574, 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [5.4527335 , 7.93892316, 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [4.81425622, 5.19947311, 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0

In [36]:
inv(A)

LinAlgError: Singular matrix

In [37]:
sum(p)

np.float64(174.7900216123369)

In [ ]:
row_norms = np.linalg.norm(p.T, axis=1)  # shape (m,)
norm_a_vect = row_norms[:, None]  # shape (m, 1)

array([ 4.5497978 ,  6.52736781,  9.63113719,  7.08601323, 10.3042101 ,
        5.7278518 ,  4.27155894,  5.67568931,  8.5685893 , 10.18131129,
        8.9534864 ,  2.61361003,  9.71169254,  3.79909236,  2.98629185,
       10.52145687, 12.0127504 ,  5.3821321 ,  2.92792071,  7.85532859])

In [ ]:
C = inv(A)@norm_a_vect
C

array([ 1.33811853e+02, -6.87008548e+01,  6.27279074e+17, -9.37488056e+17,
        3.71755665e+14,  6.99836462e+15,  8.42616956e+15,  3.97095588e+18,
        6.43493419e+16, -3.90449071e+18,  5.99521473e+17,  3.44509299e+16,
       -5.84050106e+17, -2.08739109e+16,  4.15441468e+17, -3.09395008e+17,
        2.26348270e+16, -1.42449154e+16,  6.49743036e+15,  1.36159911e+16])

In [ ]:
r = sqrt()